/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

/**
 *
 * @author arthu
 */
public class MenuPrincipalFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFuncionario.class.getName());

    /**
     * Creates new form MenuPrincipalFuncionario
     */
    public MenuPrincipalFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        painelFundo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbCadastro = new javax.swing.JMenu();
        miCadCliente = new javax.swing.JMenuItem();
        miCadProduto = new javax.swing.JMenuItem();
        mbRelatorio = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miRelatCliente = new javax.swing.JMenuItem();
        miRelatProduto = new javax.swing.JMenuItem();
        mbVenda = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        painelFundo.setBackground(new java.awt.Color(161, 126, 83));
        painelFundo.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 0));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        mbCadastro.setBackground(new java.awt.Color(153, 102, 0));
        mbCadastro.setForeground(new java.awt.Color(0, 0, 0));
        mbCadastro.setText("Cadastro");

        miCadCliente.setText("Cliente");
        miCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadClienteActionPerformed(evt);
            }
        });
        mbCadastro.add(miCadCliente);

        miCadProduto.setText("Produto");
        miCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadProdutoActionPerformed(evt);
            }
        });
        mbCadastro.add(miCadProduto);

        jMenuBar1.add(mbCadastro);

        mbRelatorio.setText("Relatório");
        mbRelatorio.add(jSeparator1);

        miRelatCliente.setText("Clientes");
        miRelatCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatClienteActionPerformed(evt);
            }
        });
        mbRelatorio.add(miRelatCliente);

        miRelatProduto.setText("Produtos");
        mbRelatorio.add(miRelatProduto);

        jMenuBar1.add(mbRelatorio);

        mbVenda.setText("Vendas");
        jMenuBar1.add(mbVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProdutoActionPerformed
        this.setVisible(false);
        
        CadastrarProduto cadProduto = new CadastrarProduto();
        cadProduto.setVisible(true);
    }//GEN-LAST:event_miCadProdutoActionPerformed

    private void miCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadClienteActionPerformed
        this.setVisible(false);
        
        CadastrarCliente cadCliente = new CadastrarCliente();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_miCadClienteActionPerformed

    private void miRelatClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatClienteActionPerformed
        this.setVisible(false);
        
        ListarClientes listCliente = new ListarClientes();
        listCliente.setVisible(true);
    }//GEN-LAST:event_miRelatClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mbCadastro;
    private javax.swing.JMenu mbRelatorio;
    private javax.swing.JMenu mbVenda;
    private javax.swing.JMenuItem miCadCliente;
    private javax.swing.JMenuItem miCadProduto;
    private javax.swing.JMenuItem miRelatCliente;
    private javax.swing.JMenuItem miRelatProduto;
    private javax.swing.JPanel painelFundo;
    // End of variables declaration//GEN-END:variables
}
